name: Mirror official site

on:
  schedule:
    - cron:  '14 1 * * *'
  workflow_dispatch: {}

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install OS dependencies
      run: sudo apt-get install jq moreutils
    - name: Mirror official site
      run: curl -o data/official-raw.csv $(jq -r .source.csv meta.json)
    - name: Commit and push if changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add data
        timestamp=$(date -u)
        git commit -m "Update official data: ${timestamp}" || exit 0
        git push
